@extends('layouts.app')

@section('title', 'Security')

@section('content')
<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4">Account / <span class="text-muted fw-light">Security</span></h4>

    @if(session('success'))
        <div class="alert alert-success alert-dismissible py-2" role="alert">
            {{ session('success') }}
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
    @endif
    @if(session('warning'))
        <div class="alert alert-warning alert-dismissible py-2" role="alert">
            <i class="bx bx-error me-1"></i> {{ session('warning') }}
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
    @endif

    {{-- 2FA Status Card --}}
    <div class="card mb-4">
        <div class="card-header d-flex align-items-center justify-content-between py-3">
            <h5 class="mb-0">Two-Factor Authentication</h5>
            @if($enabled)
                <span class="badge bg-label-success fs-6">
                    <i class="bx bx-shield-check me-1"></i> Enabled
                </span>
            @else
                <span class="badge bg-label-secondary fs-6">
                    <i class="bx bx-shield-x me-1"></i> Disabled
                </span>
            @endif
        </div>
        <div class="card-body">
            @if($enabled)
                {{-- Current method info --}}
                <div class="d-flex align-items-center gap-3 mb-4 p-3 bg-lighter rounded">
                    @php
                        $methodIcon = match($user->two_factor_type) {
                            'email' => 'bx-envelope',
                            'sms'   => 'bx-mobile-alt',
                            'totp'  => 'bx-qr',
                            default => 'bx-lock',
                        };
                        $methodLabel = match($user->two_factor_type) {
                            'email' => 'Email OTP',
                            'sms'   => 'SMS OTP',
                            'totp'  => 'Authenticator App (TOTP)',
                            default => 'Unknown',
                        };
                    @endphp
                    <div class="avatar">
                        <span class="avatar-initial rounded bg-label-primary">
                            <i class="bx {{ $methodIcon }} fs-4"></i>
                        </span>
                    </div>
                    <div>
                        <h6 class="mb-0">{{ $methodLabel }}</h6>
                        @if($user->two_factor_type === 'sms')
                            <small class="text-muted">{{ $user->two_factor_phone }}</small>
                        @elseif($user->two_factor_type === 'email')
                            <small class="text-muted">{{ $user->email }}</small>
                        @else
                            <small class="text-muted">Codes generated by your authenticator app</small>
                        @endif
                    </div>
                </div>

                {{-- Switch method --}}
                <p class="mb-2 fw-semibold">Switch to a different method</p>
                <div class="row g-3 mb-4">
                    @foreach([
                        ['email', 'bx-envelope', 'Email OTP', 'A one-time code sent to your email.'],
                        ['sms',   'bx-mobile-alt', 'SMS OTP', 'A one-time code sent to your phone.'],
                        ['totp',  'bx-qr', 'Authenticator App', 'Time-based codes from an app like Google Authenticator.'],
                    ] as [$method, $icon, $label, $desc])
                    @if($user->two_factor_type !== $method)
                    <div class="col-md-4">
                        <div class="card border h-100 mb-0">
                            <div class="card-body p-3">
                                <div class="d-flex align-items-center gap-2 mb-2">
                                    <i class="bx {{ $icon }} fs-5 text-primary"></i>
                                    <h6 class="mb-0">{{ $label }}</h6>
                                </div>
                                <p class="text-muted mb-3" style="font-size:.8rem;">{{ $desc }}</p>
                                <button class="btn btn-outline-primary btn-sm w-100"
                                        data-bs-toggle="modal"
                                        data-bs-target="#enableModal"
                                        data-method="{{ $method }}">
                                    Switch to {{ $label }}
                                </button>
                            </div>
                        </div>
                    </div>
                    @endif
                    @endforeach
                </div>

                {{-- Disable 2FA --}}
                <hr>
                <p class="mb-2 text-muted small">Disabling 2FA reduces your account security. You will need to enter your current password.</p>
                <button class="btn btn-outline-danger btn-sm" data-bs-toggle="modal" data-bs-target="#disableModal">
                    <i class="bx bx-lock-open me-1"></i> Disable 2FA
                </button>

            @else
                {{-- Enable 2FA --}}
                <p class="text-muted mb-4">
                    Two-factor authentication adds an extra layer of security to your account. Choose a method below.
                </p>
                <div class="row g-3">
                    @foreach([
                        ['email', 'bx-envelope', 'Email OTP', 'A one-time code is sent to your email address each time you log in.', 'primary'],
                        ['sms',   'bx-mobile-alt', 'SMS OTP', 'A one-time code is sent via SMS to your phone number.', 'success'],
                        ['totp',  'bx-qr', 'Authenticator App', 'Use Google Authenticator, Authy, or any TOTP app to generate codes.', 'info'],
                    ] as [$method, $icon, $label, $desc, $color])
                    <div class="col-md-4">
                        <div class="card border h-100 mb-0">
                            <div class="card-body p-3 text-center">
                                <div class="avatar avatar-md mb-3 mx-auto">
                                    <span class="avatar-initial rounded-circle bg-label-{{ $color }}">
                                        <i class="bx {{ $icon }} fs-4"></i>
                                    </span>
                                </div>
                                <h6>{{ $label }}</h6>
                                <p class="text-muted mb-3" style="font-size:.8rem;">{{ $desc }}</p>
                                <button class="btn btn-{{ $color }} btn-sm"
                                        data-bs-toggle="modal"
                                        data-bs-target="#enableModal"
                                        data-method="{{ $method }}">
                                    Enable
                                </button>
                            </div>
                        </div>
                    </div>
                    @endforeach
                </div>
            @endif
        </div>
    </div>
</div>

{{-- Enable / Switch modal --}}
<div class="modal fade" id="enableModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Enable Two-Factor Authentication</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <form action="{{ route('settings.two-factor.enable') }}" method="POST">
                @csrf
                <input type="hidden" name="method" id="modalMethod" value="">
                <div class="modal-body">
                    <p id="modalDesc" class="text-muted mb-3"></p>
                    <div id="phoneGroup" class="d-none">
                        <label class="form-label" for="phone">Phone Number <span class="text-danger">*</span></label>
                        <input type="tel" id="phone" name="phone" class="form-control"
                               placeholder="+1 555 000 0000">
                        <div class="form-text">Include country code, e.g. +1 for US.</div>
                        @error('phone')<div class="text-danger small mt-1">{{ $message }}</div>@enderror
                    </div>
                    @error('method')<div class="text-danger small">{{ $message }}</div>@enderror
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-label-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Continue</button>
                </div>
            </form>
        </div>
    </div>
</div>

{{-- Disable modal --}}
@if($enabled)
<div class="modal fade" id="disableModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Disable Two-Factor Authentication</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <form action="{{ route('settings.two-factor.disable') }}" method="POST">
                @csrf
                @method('DELETE')
                <div class="modal-body">
                    <p class="text-muted">Confirm your current password to disable 2FA.</p>
                    <label class="form-label" for="disablePassword">Current Password</label>
                    <input type="password" id="disablePassword" name="password"
                           class="form-control @error('password') is-invalid @enderror">
                    @error('password')<div class="invalid-feedback">{{ $message }}</div>@enderror
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-label-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-danger">Disable 2FA</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endif
@endsection

@push('page-js')
<script>
(function () {
    const descs = {
        email : 'A one-time code will be sent to your email address each time you log in.',
        sms   : 'A one-time code will be sent to your phone via SMS.',
        totp  : 'You will scan a QR code with your authenticator app and enter a confirmation code.',
    };

    document.getElementById('enableModal')?.addEventListener('show.bs.modal', function (e) {
        const method = e.relatedTarget?.dataset.method ?? 'email';
        document.getElementById('modalMethod').value = method;
        document.getElementById('modalDesc').textContent = descs[method] ?? '';
        const pg = document.getElementById('phoneGroup');
        const pi = document.getElementById('phone');
        if (method === 'sms') {
            pg.classList.remove('d-none');
            pi.required = true;
        } else {
            pg.classList.add('d-none');
            pi.required = false;
            pi.value = '';
        }
    });
})();
</script>
@endpush
